### ISSUE TITLE
Corrupt LoadingBar?

### ISSUE THREAD

**Issue by haekelmeister** [vapor/console-kit#141]
I wrote a little command line tool in Xcode. While the tool is doing his job I'd like to indicate that the tool is working with a little loading bar. For this I've chosen the `LoadingBar`. Unfortunately the loading bar behaves not as expected.

Given is the following code:

```swift
import ConsoleKit
import Foundation

let loadingBar = Terminal().loadingBar(title: "TEST")

loadingBar.start()
sleep(3)
loadingBar.succeed()
```

When I run this code I get the following output:

<img width="495" alt="LoadingBarWrong" src="https://user-images.githubusercontent.com/10478634/82916649-97cb6980-9f72-11ea-8c9a-aeaa754526f7.png">

The output seems to be wrong because I expect every update on one/the same line and not each print in a separate line. But when I run the very same code with `swift run` on the console the output is as expected:

<img width="575" alt="LoadingBarOk" src="https://user-images.githubusercontent.com/10478634/82916696-a6b21c00-9f72-11ea-8ec3-6bf471010cee.png">

Does anyone know whether this is a bug or do I have to configure the console differently?

**Comment by tanner0101** [comment]
This is because Xcode does not support the special terminal commands for deleting lines. You can use `#if Xcode` to fallback to a non-animated option.

```swift
let console = Terminal()
#if Xcode
console.print("Loading...")
#else
let loadingBar = console.loadingBar(title: "TEST")
loadingBar.start()
sleep(3)
loadingBar.succeed()
```
