### ISSUE TITLE
Persisting prompts and options

### ISSUE THREAD

**Issue by bjo0** [vapor/console-kit#142]
The documentation reads:
```
    /// Upon answering, the prompt and options will be cleared from the console and only the output will remain:
```

I was building a console tool for users who aren't very comfortable on the command line, and I'm concerned that it may be disorienting for them to have the prompt and options disappear after they answer. I was concerned enough about it that I added in a 1 second pause after each choice.

**Comment by gwynne** [comment]
Closing due to age, please reopen if this is still a problem
