### ISSUE TITLE
Concurrency warnings

### ISSUE THREAD

**Issue by chibombo** [vapor/console-kit#189]
### Describe the bug

We are having some warnings at the moment that we are building a vapor project

### To Reproduce

Using the latest version `4.85.0`, the displayed warnings are like this when we build:

```
.build/checkouts/console-kit/Sources/ConsoleKit/Activity/ActivityIndicator.swift:1:1: remark: add '@preconcurrency' to suppress 'Sendable'-related warnings from module 'Dispatch'
import Dispatch
```

```
.build/checkouts/vapor/Sources/Vapor/Validation/Validators/CharacterSet.swift:1:1: remark: add '@preconcurrency' to suppress 'Sendable'-related warnings from module 'Foundation'
import Foundation 
```

```
.build/checkouts/vapor/Sources/Vapor/Sessions/MemorySessions.swift:1:1: remark: add '@preconcurrency' to suppress 'Sendable'-related warnings from module 'Dispatch'
import Foundation
```
### Expected behavior

No warnings

### Environment

* Vapor Framework version: `4.85.0`
* Vapor Toolbox version: `18.6.0`
* OS version: Ubuntu `22.04`

### Additional context
The context is [this](https://github.com/apple/swift-evolution/blob/main/proposals/0337-support-incremental-migration-to-concurrency-checking.md)

**Comment by 0xTim** [comment]
The Vapor warnings will be fixed in https://github.com/vapor/vapor/pull/3093
