### ISSUE TITLE
Method to detect pressed key(s) and returning the keyCode(s)

### ISSUE THREAD

**Issue by pakLebah** [vapor/console-kit#72]
Please add a method to detect single or multiple pressed keys and returning the keyCode(s). This feature is required for accepting password input or screen navigation control (console games?). If you have ever used Pascal and utilized the famous `CRT` unit, you'll know the `ReadKey()` and `KeyPressed()` functions that provide such ability.

Thank you.

**Comment by calebkleveter** [comment]
I really like the idea of this feature, but it is not required for secure input. That is already supported by clearing the current line on every key press.

**Comment by gwynne** [comment]
At this time there is no plan to do this, as it heads in the direction of trying to make ConsoleKit a Swift version of ncurses - arguably a worthwhile thing, but not something we're planning right now (though I say nothing about the future!)
