### ISSUE TITLE
Command Options do not pick up default values.

### ISSUE THREAD

**Issue by EricWVGG** [vapor/console-kit#76]
sample project: https://github.com/EricWVGG/vapor-command-problem

This command should respect "one" as the default value for "answer"
`vapor run quiz` 
Expected response: `better not be the middle one`
Actual response: `What?`

**Comment by EricWVGG** [comment]
Thank you for addressing my other issue. Regarding this one, this still strikes me as broken. Is it filed in the correct repo?

**Comment by vi4m** [comment]
It works when you procide empty "option"

` vapor run quiz --answer`

**Comment by vi4m** [comment]
Ok, I re-read the documentation, and it seems, it's really a bug here. Have fix already :)

**Comment by vi4m** [comment]
Fixed here: https://github.com/vapor/console/pull/79
