### ISSUE TITLE
UnvalidatedCommand

### ISSUE THREAD

**Issue by tanner0101** [vapor/console-kit#90]
A new protocol `UnvalidatedCommand` that did not require a command to pre-define it's supported arguments and options would be useful for implementing commands like `vapor run` that forward to an underlying program.

**Comment by rderik** [comment]
Yes, another case is when we would like to inspect the parameters so the command handles arguments from the STDIN or from files. To exemplify the take the Unix command `head`

we could send arguments to `head` through a pipe:
`cat Package.swift | head`
or we can send filenames as arguments to command.
` head Package.swift README.md`

Ruby handles these cases using `ARGF`. for an example: https://rderik.com/blog/shell-friendly-ruby-scripts/. If we could provide something similar I think it would be helpful to build commands that are friendly to be composed not just stand-alone commands.

**Comment by calebkleveter** [comment]
In Console 4, would it be ok to do this?

```swift
final class Run: Command {
    struct Signature: CommandSignature { }
    let signature: Run.Signature = Signature()

    // ....
}
```

There isn't any signature validation unless you set `strict` to `true`, so it would work.

**Comment by tanner0101** [comment]
This now exists as `AnyCommand`.
